config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :first_name, presence: true, length: {minimum: 1, maximum: 50 }
  validates :last_name, presence: true, length: {minimum: 1, maximum: 50 }
  validates :station, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {minimum: 1, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            length: { maximum: 255 }, 
            format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :destroy, :update]
  def show
   set_patient
  end
  

  def index
      @patients=Patient.all
  end

  def new
      @patient = Patient.new
  end

  def edit
   set_patient
  end
  

  def create
      @patient = Patient.new(params.require(:patient).permit(:first_name, :last_name, :station, :room))
      if @patient.save
        flash[:notice] = "Patient wurde angelegt"
        redirect_to @patient
      else
        render "new"
      end
  end

  def update 
    if @patient.update(params.require(:patient).permit(:first_name, :last_name, :station, :room))
      flash[:notice] = "Erfolgreich bearbeitet"
      redirect_to @patient
    else 
      render "edit" 
    end
  end

  def destroy
    if @patient.destroy
      redirect_to patients_path
      flash[:notice] = @patient.first_name + " " + @patient.last_name + " wurde gelöscht!"
    end
  end

  private
    
  def set_patient
    @patient = Patient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class= "container mt-3 ">
  <%= link_to  image_tag("logo-bdh.png"), root_path%>
  

  
</div>

app/views/layouts/_messages.html.erb
  
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light ">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto ">
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Patient
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to  "Patient*in anlegen", new_patient_path(), class:"dropdown-item" %>
            <%= link_to  "Alle Patienten", patients_path(), class:"dropdown-item" %>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2 " type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientenMenue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/header" %>
    <%= render  "layouts/navigation" %>
    <%= render  "layouts/messages" %> 
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patienten Menü</title>
</head>
<body>
  <h1 class="text-center">Home</h1>
</body>
</html>

app/views/patients/_form.html.erb
<div class="container mt-1">
  <div class = "row justify-content-center text-white ">
    <div class = "col-10 ">
      <%= render  "shared/errors",obj: @patient %>
      <%= form_with(model: @patient, class: "shadow p-3 mb-3 bg-box rounded", local: true) do |f| %>
      
      <div class="form-group ">   
        <div class="col-10">
          <%= f.text_field :first_name, class: "form-control shadow rounded", placeholder: "Vorname" %>
        </div>
      </div>

            <div class="form-group ">   
        <div class="col-10">
          <%= f.text_field :last_name, class: "form-control shadow rounded", placeholder: "Nachname" %>
        </div>
      </div>

        <div class="form-group ">   
            <div class="col-10 text-secondary">
               <%= f.select :station, options_for_select([
                        ["Station", ""], 
                        "1", 
                        "2", 
                        "3", 
                        "4", 
                        "5",
                        "6",
                        "7"]), 
                        {}, { class: "form form-group form-control shadow" } %>

            </div>
        </div>

            <div class="form-group">   

        <div class="col-10">
          <%= f.text_field :room, class: "form-control shadow rounded", placeholder: "Raum" %>
        </div>
      </div>

        <%= f.submit :value => "Okay", class: "btn ml-3 bg-bdh text-white "  %>
        
      </div>
       
      <%end%>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<h1 class="text-center"><%= @patient.first_name + " " + @patient.last_name %> bearbeiten</h1>
<h4 class="text-center">Station: <%= @patient.station %></h4>
<%= render  "form" %>

app/views/patients/index.html.erb
<h1 class="text-center">Liste aller Patienten</h1>
<div class="container">
  <div id="list-example" class="list-group">
  <a class="list-group-item list-group-item-action" href="#list-item-1">Station 1</a>
  <a class="list-group-item list-group-item-action" href="#list-item-2">Station 2</a>
  <a class="list-group-item list-group-item-action" href="#list-item-3">Station 3</a>
  <a class="list-group-item list-group-item-action" href="#list-item-4">Station 4</a>
  <a class="list-group-item list-group-item-action" href="#list-item-5">Station 5</a>
  <a class="list-group-item list-group-item-action" href="#list-item-6">Station 6</a>
  <a class="list-group-item list-group-item-action" href="#list-item-7">Station 7</a>
</div>
  <%station = 0
    7.times do
      station += 1
  %>
  <div data-spy="scroll" data-target="#list-example" data-offset="0" class="scrollspy-example">
  <h4 id="list-item-<%=station%>">Station <%= station %></h4>
    <table class="table">
      <thead class="thead-light">
      <tr>
        <th scope="col">Vorname</th>
        <th scope="col">Nachname</th>
        <th scope="col">Station</th>
        <th scope="col">Raum</th>
        <th scope="col">Aktion</th>
      </tr>
      </thead>
      <tbody>
        <%Patient.where(station: station).find_each do |patient|%>
          <tr>
            <td><%= patient.first_name %></td>
            <td><%= patient.last_name%></td>
            <td><%= patient.station %></td>
            <td><%= patient.room %></td>
            <td>
              <%= link_to "Bearbeiten", edit_patient_path(patient), class: "btn btn-outline-success" %>
              <%= link_to "Löschen", patient_path(patient), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
        <%end%>  
      </tbody>
    </table>
    </div>
  <%end%>

</div> 

app/views/patients/new.html.erb
<h1 class="text-center">Neuen Patient*in anlegen</h1>
<%= render  "form" %>

app/views/patients/show.html.erb
<div id="page-content">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic border-bottom-1">
            erstellt von <%= '#' %>
           
          </div>
          <div class="card-body ">
            <h4 class="card-title text-center"><%= @patient.first_name + " " + @patient.last_name%></h4>

            <div class="card-text text-center">Station: <%= @patient.station%></div>
            <div class="card-text text-center mb-4">Raum: <%= @patient.room%></div>
           
            <%= link_to "Bearbeiten", edit_patient_path(@patient), class: "btn btn-outline-success" %>
            <%= link_to "Löschen", patient_path(@patient), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            
          </div>
          <div class="card-footer text-muted">
            <small>erstellt am <%= @patient.created_at %>, 
            zuletzt bearbeitet am <%= @patient.updated_at %></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/shared/_errors.html.erb
<%if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        
        <p><strong>ERRORS:</strong></p>
        
        <ul>
            <% obj.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
            <%end%>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<%end%>  